### ISSUE TITLE
作者这个项目还更新吗?

### ISSUE THREAD

**Issue by Goojoe** [fangxx3863/telegraph2epub#1]
我希望使用单程序cli,而不依赖python环境,这样使用方便一些,也方便分享此工具给其他人使用
Releases的程序是交互式,这点不太好使用参数配置

**Comment by fangxx3863** [comment]
（主要是他能用我就懒得更新了，发布的程序也可以使用cli的

**Comment by Goojoe** [comment]
啊啊,抱歉,点开就能用还以为只能交互式使用,刚才试了Releases的程序是可以传递参数的
